import { GadgetConnection } from "./GadgetConnection";
import { GadgetRecord } from "./GadgetRecord";
import { GadgetRecordList } from "./GadgetRecordList";

/**
 * Object representing one model's API in a high level way
 * This is a generic interface. Concrete ones are generated by Gadget, */
export interface ModelManager {
  connection: GadgetConnection;
  findOne(id: string, options: any): Promise<GadgetRecord<any>>;
  findMany(options: any): Promise<GadgetRecordList<any>>;
}
