import type { GadgetConnection } from "./GadgetConnection.js";
import { GadgetRecord, GadgetRecord_ } from "./GadgetRecord.js";
import type { GadgetRecordList } from "./GadgetRecordList.js";

export type AnyModelFinderMetadata = {
  /** The name of the GraphQL API field that should be called for this operation */
  operationName: string;
  /** The model's api identifier */
  modelApiIdentifier: string;
  /** What fields to select from the GraphQL API if no explicit selection is passed */
  defaultSelection: Record<string, any>;
  /** A namespace this operation is nested in. Absent for old clients or root-namespaced operations */
  namespace?: string | string[] | null;
  /** Type-time only type member used for strong typing of finders  */
  selectionType: any;
  /** Type-time only type member used for strong typing of finders  */
  optionsType: any;
  /** Type-time only type member used for strong typing of finders  */
  schemaType: any | null;
};

/**
 * Object representing one model's API in a high level way
 * This is a generic interface. Concrete ones are generated by Gadget, */
export interface AnyModelManager {
  connection: GadgetConnection;
  findOne: (<RecordType extends GadgetRecord_<any> = GadgetRecord<any>>(id: string, options: any) => Promise<RecordType>) &
    AnyModelFinderMetadata;
  findMany: (<RecordType extends GadgetRecord_<any> = GadgetRecord<any>>(options: any) => Promise<GadgetRecordList<any, RecordType>>) &
    AnyModelFinderMetadata;
  findFirst: (<RecordType extends GadgetRecord_<any> = GadgetRecord<any>>(options: any) => Promise<RecordType>) & AnyModelFinderMetadata;
  maybeFindFirst<RecordType extends GadgetRecord_<any> = GadgetRecord<any>>(options: any): Promise<RecordType | null>;
  maybeFindOne<RecordType extends GadgetRecord_<any> = GadgetRecord<any>>(id: string, options: any): Promise<RecordType | null>;
}
