export const widgetModelMetadata = {
  data: {
    gadgetMeta: {
      model: {
        apiIdentifier: "widget",
        namespace: [],
        name: "Widget",
        fields: [
          {
            name: "Id",
            apiIdentifier: "id",
            fieldType: "ID",
            requiredArgumentForInput: true,
            sortable: true,
            filterable: true,
            __typename: "GadgetModelField",
            configuration: {
              __typename: "GadgetGenericFieldConfig",
              fieldType: "ID",
              validations: [
                {
                  __typename: "GadgetGenericFieldValidation",
                  name: "Uniqueness",
                  specID: "gadget/validation/unique",
                },
                {
                  __typename: "GadgetGenericFieldValidation",
                  name: "Required",
                  specID: "gadget/validation/required",
                },
              ],
            },
          },
          {
            name: "Name",
            apiIdentifier: "name",
            fieldType: "String",
            requiredArgumentForInput: true,
            sortable: true,
            filterable: true,
            __typename: "GadgetModelField",
            configuration: {
              __typename: "GadgetGenericFieldConfig",
              fieldType: "String",
              validations: [
                {
                  __typename: "GadgetGenericFieldValidation",
                  name: "Required",
                  specID: "gadget/validation/required",
                },
              ],
            },
          },
          {
            name: "Inventory count",
            apiIdentifier: "inventoryCount",
            fieldType: "Number",
            requiredArgumentForInput: true,
            sortable: true,
            filterable: true,
            __typename: "GadgetModelField",
            configuration: {
              __typename: "GadgetNumberConfig",
              fieldType: "Number",
              validations: [
                {
                  __typename: "GadgetRangeFieldValidation",
                  name: "Number range",
                  specID: "gadget/validation/number-range",
                  min: 0,
                  max: null,
                },
                {
                  __typename: "GadgetGenericFieldValidation",
                  name: "Required",
                  specID: "gadget/validation/required",
                },
              ],
              decimals: null,
            },
          },
          {
            name: "Is checked",
            apiIdentifier: "isChecked",
            fieldType: "Boolean",
            requiredArgumentForInput: false,
            sortable: true,
            filterable: true,
            __typename: "GadgetModelField",
            configuration: {
              __typename: "GadgetGenericFieldConfig",
              fieldType: "Boolean",
              validations: [],
            },
          },
          {
            name: "Must be long string",
            apiIdentifier: "mustBeLongString",
            fieldType: "String",
            requiredArgumentForInput: false,
            sortable: true,
            filterable: true,
            __typename: "GadgetModelField",
            configuration: {
              __typename: "GadgetGenericFieldConfig",
              fieldType: "String",
              validations: [
                {
                  __typename: "GadgetRangeFieldValidation",
                  name: "String length range",
                  specID: "gadget/validation/string-size",
                  min: 20,
                  max: null,
                },
              ],
            },
          },
          {
            name: "Category",
            apiIdentifier: "category",
            fieldType: "Enum",
            requiredArgumentForInput: false,
            sortable: true,
            filterable: true,
            __typename: "GadgetModelField",
            configuration: {
              __typename: "GadgetEnumConfig",
              fieldType: "Enum",
              validations: [],
              allowMultiple: true,
              allowOther: false,
              options: [
                {
                  name: "Whoosits",
                  color: "#FCFCFC",
                  __typename: "GadgetEnumOption",
                },
                {
                  name: "Whatsits",
                  color: "#606060",
                  __typename: "GadgetEnumOption",
                },
                {
                  name: "Galores",
                  color: "#DF2222",
                  __typename: "GadgetEnumOption",
                },
              ],
            },
          },
          {
            name: "Starts at",
            apiIdentifier: "startsAt",
            fieldType: "DateTime",
            requiredArgumentForInput: false,
            sortable: true,
            filterable: true,
            __typename: "GadgetModelField",
            configuration: {
              __typename: "GadgetDateTimeConfig",
              fieldType: "DateTime",
              validations: [],
              includeTime: true,
            },
          },
          {
            name: "Birthday",
            apiIdentifier: "birthday",
            fieldType: "DateTime",
            requiredArgumentForInput: false,
            sortable: true,
            filterable: true,
            __typename: "GadgetModelField",
            configuration: {
              __typename: "GadgetDateTimeConfig",
              fieldType: "DateTime",
              validations: [],
              includeTime: false,
            },
          },
          {
            name: "Section",
            apiIdentifier: "section",
            fieldType: "BelongsTo",
            requiredArgumentForInput: false,
            sortable: false,
            filterable: true,
            __typename: "GadgetModelField",
            configuration: {
              __typename: "GadgetBelongsToConfig",
              fieldType: "BelongsTo",
              validations: [],
              relatedModel: {
                key: "DataModel-section",
                apiIdentifier: "section",
                namespace: [],
                defaultDisplayField: {
                  apiIdentifier: "name",
                  __typename: "GadgetModelField",
                },
                __typename: "GadgetModel",
              },
            },
          },
          {
            name: "Gizmos",
            apiIdentifier: "gizmos",
            fieldType: "HasMany",
            requiredArgumentForInput: false,
            sortable: false,
            filterable: false,
            __typename: "GadgetModelField",
            configuration: {
              __typename: "GadgetHasManyConfig",
              fieldType: "HasMany",
              validations: [],
              relatedModel: {
                key: "DataModel-gizmo",
                apiIdentifier: "gizmo",
                namespace: [],
                defaultDisplayField: {
                  apiIdentifier: "name",
                  __typename: "GadgetModelField",
                },
                __typename: "GadgetModel",
              },
              inverseField: {
                apiIdentifier: "widget",
                __typename: "GadgetModelField",
              },
            },
          },
          {
            name: "Anything",
            apiIdentifier: "anything",
            fieldType: "JSON",
            requiredArgumentForInput: false,
            sortable: true,
            filterable: true,
            __typename: "GadgetModelField",
            configuration: {
              __typename: "GadgetGenericFieldConfig",
              fieldType: "JSON",
              validations: [],
            },
          },
          {
            name: "Description",
            apiIdentifier: "description",
            fieldType: "RichText",
            requiredArgumentForInput: false,
            sortable: true,
            filterable: true,
            __typename: "GadgetModelField",
            configuration: {
              __typename: "GadgetGenericFieldConfig",
              fieldType: "RichText",
              validations: [],
            },
          },
          {
            name: "Metafields",
            apiIdentifier: "metafields",
            fieldType: "JSON",
            requiredArgumentForInput: false,
            sortable: true,
            filterable: true,
            __typename: "GadgetModelField",
            configuration: {
              __typename: "GadgetGenericFieldConfig",
              fieldType: "JSON",
              validations: [],
            },
          },
          {
            name: "Roles",
            apiIdentifier: "roles",
            fieldType: "RoleAssignments",
            requiredArgumentForInput: false,
            sortable: false,
            filterable: true,
            __typename: "GadgetModelField",
            configuration: {
              __typename: "GadgetGenericFieldConfig",
              fieldType: "RoleAssignments",
              validations: [],
            },
          },
          {
            name: "In stock",
            apiIdentifier: "inStock",
            fieldType: "Computed",
            requiredArgumentForInput: false,
            sortable: false,
            filterable: true,
            __typename: "GadgetModelField",
            configuration: {
              __typename: "GadgetGenericFieldConfig",
              fieldType: "Computed",
              validations: [],
            },
          },
          {
            name: "Color",
            apiIdentifier: "color",
            fieldType: "Color",
            requiredArgumentForInput: false,
            sortable: true,
            filterable: true,
            __typename: "GadgetModelField",
            configuration: {
              __typename: "GadgetGenericFieldConfig",
              fieldType: "Color",
              validations: [
                {
                  __typename: "GadgetGenericFieldValidation",
                  name: "Color",
                  specID: "gadget/validation/color",
                },
              ],
            },
          },
          {
            name: "Secret key",
            apiIdentifier: "secretKey",
            fieldType: "EncryptedString",
            requiredArgumentForInput: false,
            sortable: false,
            filterable: false,
            __typename: "GadgetModelField",
            configuration: {
              __typename: "GadgetGenericFieldConfig",
              fieldType: "EncryptedString",
              validations: [],
            },
          },
          {
            name: "Embedding",
            apiIdentifier: "embedding",
            fieldType: "Vector",
            requiredArgumentForInput: false,
            sortable: true,
            filterable: true,
            __typename: "GadgetModelField",
            configuration: {
              __typename: "GadgetGenericFieldConfig",
              fieldType: "Vector",
              validations: [],
            },
          },
          {
            name: "Created at",
            apiIdentifier: "createdAt",
            fieldType: "DateTime",
            requiredArgumentForInput: true,
            sortable: true,
            filterable: true,
            __typename: "GadgetModelField",
            configuration: {
              __typename: "GadgetDateTimeConfig",
              fieldType: "DateTime",
              validations: [
                {
                  __typename: "GadgetGenericFieldValidation",
                  name: "Required",
                  specID: "gadget/validation/required",
                },
              ],
              includeTime: true,
            },
          },
          {
            name: "Updated at",
            apiIdentifier: "updatedAt",
            fieldType: "DateTime",
            requiredArgumentForInput: true,
            sortable: true,
            filterable: true,
            __typename: "GadgetModelField",
            configuration: {
              __typename: "GadgetDateTimeConfig",
              fieldType: "DateTime",
              validations: [
                {
                  __typename: "GadgetGenericFieldValidation",
                  name: "Required",
                  specID: "gadget/validation/required",
                },
              ],
              includeTime: true,
            },
          },
        ],
        __typename: "GadgetModel",
      },
      __typename: "GadgetApplicationMeta",
    },
  },
};

export const first50WidgetRecords = {
  data: {
    widgets: {
      pageInfo: {
        hasNextPage: true,
        hasPreviousPage: false,
        startCursor: "eyJpZCI6IjcifQ==",
        endCursor: "eyJpZCI6IjU2In0=",
        __typename: "PageInfo",
      },
      edges: [
        {
          cursor: "eyJpZCI6IjcifQ==",
          node: {
            __typename: "Widget",
            id: "7",
            anything: null,
            birthday: "2002-02-02",
            category: [],
            color: null,
            createdAt: "2023-09-07T19:18:50.262Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 1,
            isChecked: false,
            metafields: null,
            mustBeLongString: null,
            name: "foo",
            roles: [],
            secretKey: "skey",
            startsAt: null,
            updatedAt: "2024-07-17T20:55:36.191Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjgifQ==",
          node: {
            __typename: "Widget",
            id: "8",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-09-07T19:18:50.431Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 2,
            isChecked: true,
            metafields: null,
            mustBeLongString: null,
            name: "bar",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2024-07-17T20:38:04.359Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjkifQ==",
          node: {
            __typename: "Widget",
            id: "9",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-09-07T19:18:50.553Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 3,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "baz",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-09-21T17:19:11.223Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjEwIn0=",
          node: {
            __typename: "Widget",
            id: "10",
            anything: "hello",
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T17:55:10.264Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record Sun Oct 01 2023 13:55:09 GMT-0400 (Eastern Daylight Time)",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T17:55:10.264Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjExIn0=",
          node: {
            __typename: "Widget",
            id: "11",
            anything: "hello",
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T17:55:19.004Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record Sun Oct 01 2023 13:55:18 GMT-0400 (Eastern Daylight Time)",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T17:55:19.004Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjEyIn0=",
          node: {
            __typename: "Widget",
            id: "12",
            anything: "hello",
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:10:03.958Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record Sun Oct 01 2023 14:10:00 GMT-0400 (Eastern Daylight Time)",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:10:03.958Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjEzIn0=",
          node: {
            __typename: "Widget",
            id: "13",
            anything: "hello",
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:11:24.787Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record Sun Oct 01 2023 14:11:24 GMT-0400 (Eastern Daylight Time)",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:11:24.787Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjE0In0=",
          node: {
            __typename: "Widget",
            id: "14",
            anything: "hello",
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:11:33.556Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record Sun Oct 01 2023 14:11:33 GMT-0400 (Eastern Daylight Time)",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:11:33.556Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjE1In0=",
          node: {
            __typename: "Widget",
            id: "15",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:12:05.935Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:12:05.935Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjE2In0=",
          node: {
            __typename: "Widget",
            id: "16",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:12:07.234Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:12:07.234Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjE3In0=",
          node: {
            __typename: "Widget",
            id: "17",
            anything: "hello",
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:12:13.466Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record Sun Oct 01 2023 14:12:13 GMT-0400 (Eastern Daylight Time)",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:12:13.466Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjE4In0=",
          node: {
            __typename: "Widget",
            id: "18",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:12:20.194Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:12:20.194Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjE5In0=",
          node: {
            __typename: "Widget",
            id: "19",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:12:24.518Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:12:24.518Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjIwIn0=",
          node: {
            __typename: "Widget",
            id: "20",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:12:25.960Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:12:25.960Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjIxIn0=",
          node: {
            __typename: "Widget",
            id: "21",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:12:28.661Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:12:28.661Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjIyIn0=",
          node: {
            __typename: "Widget",
            id: "22",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:12:30.054Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:12:30.054Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjIzIn0=",
          node: {
            __typename: "Widget",
            id: "23",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:12:31.481Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:12:31.481Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjI0In0=",
          node: {
            __typename: "Widget",
            id: "24",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:12:36.420Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 111,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "backfilled",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2024-07-16T19:44:57.797Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjI1In0=",
          node: {
            __typename: "Widget",
            id: "25",
            anything: "hello",
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:12:40.836Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record Sun Oct 01 2023 14:12:40 GMT-0400 (Eastern Daylight Time)",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:12:40.836Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjI2In0=",
          node: {
            __typename: "Widget",
            id: "26",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:13:34.237Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:13:34.237Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjI3In0=",
          node: {
            __typename: "Widget",
            id: "27",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:13:36.691Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:13:36.691Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjI4In0=",
          node: {
            __typename: "Widget",
            id: "28",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:13:45.229Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:13:45.229Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjI5In0=",
          node: {
            __typename: "Widget",
            id: "29",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:13:46.756Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 111,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "backfilled",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2024-07-16T19:44:57.865Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjMwIn0=",
          node: {
            __typename: "Widget",
            id: "30",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:13:48.499Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 111,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "backfilled",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2024-07-16T19:44:57.936Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjMxIn0=",
          node: {
            __typename: "Widget",
            id: "31",
            anything: "hello",
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:13:52.738Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record Sun Oct 01 2023 14:13:52 GMT-0400 (Eastern Daylight Time)",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:13:52.738Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjMyIn0=",
          node: {
            __typename: "Widget",
            id: "32",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:13:55.585Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:13:55.585Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjMzIn0=",
          node: {
            __typename: "Widget",
            id: "33",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:13:58.222Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 111,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "backfilled",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2024-07-16T19:44:58.006Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjM0In0=",
          node: {
            __typename: "Widget",
            id: "34",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:15:06.676Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 111,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "backfilled",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2024-07-16T19:44:58.039Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjM1In0=",
          node: {
            __typename: "Widget",
            id: "35",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:15:16.139Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:15:16.139Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjM2In0=",
          node: {
            __typename: "Widget",
            id: "36",
            anything: "hello",
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:15:16.932Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record Sun Oct 01 2023 14:15:16 GMT-0400 (Eastern Daylight Time)",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:15:16.932Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjM3In0=",
          node: {
            __typename: "Widget",
            id: "37",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:15:17.628Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 111,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "backfilled",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2024-07-16T19:44:58.066Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjM4In0=",
          node: {
            __typename: "Widget",
            id: "38",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:15:18.164Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 111,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "backfilled",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2024-07-16T19:44:58.090Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjM5In0=",
          node: {
            __typename: "Widget",
            id: "39",
            anything: "hello",
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:15:18.881Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record Sun Oct 01 2023 14:15:18 GMT-0400 (Eastern Daylight Time)",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:15:18.881Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjQwIn0=",
          node: {
            __typename: "Widget",
            id: "40",
            anything: "hello",
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:15:58.564Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record Sun Oct 01 2023 14:15:58 GMT-0400 (Eastern Daylight Time)",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:15:58.564Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjQxIn0=",
          node: {
            __typename: "Widget",
            id: "41",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:15:59.203Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 111,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "backfilled",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2024-07-16T19:44:58.114Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjQyIn0=",
          node: {
            __typename: "Widget",
            id: "42",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:16:04.165Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2024-07-09T22:02:46.524Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjQzIn0=",
          node: {
            __typename: "Widget",
            id: "43",
            anything: "hello",
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:16:11.275Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record Sun Oct 01 2023 14:16:11 GMT-0400 (Eastern Daylight Time)",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:16:11.275Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjQ0In0=",
          node: {
            __typename: "Widget",
            id: "44",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:16:14.477Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:16:14.477Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjQ1In0=",
          node: {
            __typename: "Widget",
            id: "45",
            anything: "hello",
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:16:15.225Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record Sun Oct 01 2023 14:16:14 GMT-0400 (Eastern Daylight Time)",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:16:15.225Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjQ2In0=",
          node: {
            __typename: "Widget",
            id: "46",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:16:15.976Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 111,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "backfilled",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2024-07-16T19:44:58.139Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjQ3In0=",
          node: {
            __typename: "Widget",
            id: "47",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:16:16.474Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 111,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "backfilled",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2024-07-16T19:44:58.158Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjQ4In0=",
          node: {
            __typename: "Widget",
            id: "48",
            anything: "hello",
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:16:18.993Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record Sun Oct 01 2023 14:16:18 GMT-0400 (Eastern Daylight Time)",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:16:18.993Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjQ5In0=",
          node: {
            __typename: "Widget",
            id: "49",
            anything: "hello",
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:16:23.007Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record Sun Oct 01 2023 14:16:22 GMT-0400 (Eastern Daylight Time)",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:16:23.007Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjUwIn0=",
          node: {
            __typename: "Widget",
            id: "50",
            anything: "hello",
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:16:33.613Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record Sun Oct 01 2023 14:16:33 GMT-0400 (Eastern Daylight Time)",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:16:33.613Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjUxIn0=",
          node: {
            __typename: "Widget",
            id: "51",
            anything: "hello",
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:16:53.225Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record Sun Oct 01 2023 14:16:52 GMT-0400 (Eastern Daylight Time)",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:16:53.225Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjUyIn0=",
          node: {
            __typename: "Widget",
            id: "52",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:16:53.933Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 111,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "backfilled",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2024-07-16T19:44:58.177Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjUzIn0=",
          node: {
            __typename: "Widget",
            id: "53",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:16:54.353Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 111,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "backfilled",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2024-07-16T19:44:58.193Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjU0In0=",
          node: {
            __typename: "Widget",
            id: "54",
            anything: "hello",
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:16:56.982Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record Sun Oct 01 2023 14:16:56 GMT-0400 (Eastern Daylight Time)",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:16:56.982Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjU1In0=",
          node: {
            __typename: "Widget",
            id: "55",
            anything: "hello",
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:17:11.408Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record Sun Oct 01 2023 14:17:11 GMT-0400 (Eastern Daylight Time)",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:17:11.408Z",
          },
          __typename: "WidgetEdge",
        },
        {
          cursor: "eyJpZCI6IjU2In0=",
          node: {
            __typename: "Widget",
            id: "56",
            anything: null,
            birthday: null,
            category: [],
            color: null,
            createdAt: "2023-10-01T18:30:52.976Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 42,
            isChecked: null,
            metafields: null,
            mustBeLongString: null,
            name: "test record",
            roles: [],
            secretKey: null,
            startsAt: null,
            updatedAt: "2023-10-01T18:30:52.976Z",
          },
          __typename: "WidgetEdge",
        },
      ],
      __typename: "WidgetConnection",
    },
    gadgetMeta: {
      hydrations: {
        updatedAt: "DateTime",
        startsAt: "DateTime",
        birthday: "DateTime",
        createdAt: "DateTime",
      },
      __typename: "GadgetApplicationMeta",
    },
  },
  extensions: {
    logs: "https://ggt.link/logs/114412/62efa3ded4eaed65c4309ee48de15d3a",
    traceId: "62efa3ded4eaed65c4309ee48de15d3a",
  },
};

export const mockSearchResultWidget = (searchedForWidgetName: string) => ({
  data: {
    widgets: {
      pageInfo: {
        hasNextPage: true,
        hasPreviousPage: false,
        startCursor: "eyJpZCI6IjcifQ==",
        endCursor: "eyJpZCI6IjU2In0=",
        __typename: "PageInfo",
      },
      edges: [
        {
          cursor: "eyJpZCI6IjcifQ==",
          node: {
            __typename: "Widget",
            id: "777",
            anything: null,
            birthday: "2002-02-02",
            category: [],
            color: null,
            createdAt: "2023-09-07T19:18:50.262Z",
            description: null,
            embedding: null,
            inStock: true,
            inventoryCount: 1,
            isChecked: false,
            metafields: null,
            mustBeLongString: null,
            name: searchedForWidgetName,
            roles: [],
            secretKey: "skey",
            startsAt: null,
            updatedAt: "2024-07-17T20:55:36.191Z",
          },
          __typename: "WidgetEdge",
        },
      ],

      __typename: "WidgetConnection",
    },
    gadgetMeta: {
      hydrations: {
        updatedAt: "DateTime",
        startsAt: "DateTime",
        birthday: "DateTime",
        createdAt: "DateTime",
      },
      __typename: "GadgetApplicationMeta",
    },
  },
  extensions: {
    logs: "https://ggt.link/logs/114412/62efa3ded4eaed65c4309ee48de15d3a",
    traceId: "62efa3ded4eaed65c4309ee48de15d3a",
  },
});
