import { execSync } from "child_process";
import path from "path";
import { fileURLToPath } from "url";
import { GadgetShadcnTailwindSafelistFromTailwind } from "../../../src/auto/shadcn/GadgetShadcnTailwindSafelist.js";

describe("Tailwind CSS Output Snapshot", () => {
  it("should match snapshot of Tailwind CSS output", () => {
    // Get current file directory path
    const currentFilePath = fileURLToPath(import.meta.url);
    const currentDir = path.dirname(currentFilePath);

    // Run tailwindcss CLI command and capture output
    const fullTailwindOutput = execSync("npx tailwindcss -i ./globals.css --content './src/**/*.{js,jsx,ts,tsx,html}'", {
      encoding: "utf-8",
      cwd: path.resolve(currentDir, "../../../"),
    });

    // Create snapshot of the Tailwind CSS output
    // Create snapshot of full CSS output
    expect(fullTailwindOutput).toMatchSnapshot();

    // Extract and snapshot just the class names
    const classNames = (fullTailwindOutput.match(/\.(?![0-9]+(?:\.[0-9]+)?(?:\s|{))[a-zA-Z][a-zA-Z0-9_-]*(?=[\s{])/g) || []).map(
      (className) => className.slice(1)
    );
    const uniqueClassNames = [...new Set(classNames)].sort();
    expect(uniqueClassNames).toMatchInlineSnapshot(`
      [
        "absolute",
        "animate-spin",
        "bg-accent",
        "bg-background",
        "bg-card",
        "bg-destructive",
        "bg-muted",
        "bg-primary",
        "bg-secondary",
        "bg-transparent",
        "block",
        "border",
        "border-0",
        "border-b-0",
        "border-collapse",
        "border-gray-300",
        "border-input",
        "border-l",
        "border-neutral-300",
        "border-t",
        "break-words",
        "brightness-125",
        "brightness-95",
        "com",
        "container",
        "contents",
        "cursor-pointer",
        "cursor-text",
        "dark",
        "filter",
        "fixed",
        "flex",
        "flex-1",
        "flex-col",
        "flex-grow",
        "flex-nowrap",
        "flex-row",
        "flex-shrink-0",
        "flex-wrap",
        "font-bold",
        "font-medium",
        "font-mono",
        "font-normal",
        "font-semibold",
        "gap-1",
        "gap-2",
        "gap-3",
        "gap-4",
        "grow",
        "h-10",
        "h-2",
        "h-24",
        "h-4",
        "h-5",
        "h-6",
        "h-8",
        "h-9",
        "h-fit",
        "hidden",
        "inline-flex",
        "inset-0",
        "items-center",
        "items-start",
        "justify-between",
        "justify-center",
        "justify-start",
        "leading-none",
        "left-0",
        "left-6",
        "lowercase",
        "max-w-full",
        "mb-2",
        "min-h-8",
        "ml-2",
        "ml-auto",
        "mr-1",
        "mr-2",
        "mt-2",
        "mt-4",
        "my-auto",
        "opacity-30",
        "opacity-40",
        "opacity-50",
        "outline",
        "outline-none",
        "overflow-hidden",
        "overflow-visible",
        "overflow-x-hidden",
        "overflow-y-auto",
        "p-0",
        "p-1",
        "p-2",
        "p-3",
        "p-4",
        "p-6",
        "paused",
        "pb-1",
        "pr-20",
        "pt-0",
        "pt-2",
        "pt-3",
        "pt-4",
        "px-2",
        "px-3",
        "px-4",
        "px-8",
        "py-1",
        "py-2",
        "py-3",
        "relative",
        "resize",
        "ring-1",
        "ring-ring",
        "rounded-b-md",
        "rounded-b-none",
        "rounded-md",
        "rounded-none",
        "rounded-t-md",
        "rounded-t-none",
        "rounded-xl",
        "running",
        "shadow",
        "shadow-md",
        "shadow-none",
        "shadow-sm",
        "shrink-0",
        "space-y-6",
        "static",
        "sticky",
        "table",
        "text-2xl",
        "text-base",
        "text-card-foreground",
        "text-center",
        "text-destructive-foreground",
        "text-ellipsis",
        "text-foreground",
        "text-gray-500",
        "text-left",
        "text-lg",
        "text-muted-foreground",
        "text-primary",
        "text-primary-foreground",
        "text-red-500",
        "text-secondary-foreground",
        "text-sm",
        "text-xs",
        "top-0",
        "top-full",
        "tracking-tight",
        "transform",
        "transition-colors",
        "truncate",
        "underline-offset-4",
        "uppercase",
        "visible",
        "w-32",
        "w-4",
        "w-5",
        "w-6",
        "w-8",
        "w-auto",
        "w-full",
        "whitespace-normal",
        "whitespace-nowrap",
        "z-0",
        "z-10",
        "z-20",
        "z-30",
        "z-50",
      ]
    `);

    for (const className of uniqueClassNames) {
      expect(GadgetShadcnTailwindSafelistFromTailwind).toContain(className);
    }
  });
});
